queue:
  name: Hosted Ubuntu 1604


variables:
- group: 'Terraform Service Principal'
- group: 'Terraform State'
- name: tfstate_key
  value: 'jimpaine.pre-ready-2019-H1.master.tfstate'
- name: resource_name
  value: 'jp174'
- name: agent_count
  value: '3'
- name: vm_size
  value: 'Standard_B2ms'
- name: location
  value: 'eastus'
- name: admin_user
  value: 'demouser'
- name: k8s_version
  value: '1.11.5'
- name: envPrefixName
  value: 'jphack118'
- name: retentionPolicy
  value: '90'
- name: sqlVmSize
  value: 'Standard_DS3_v2'
- name: username
  value: 'vmadmin'
- name: diskType
  value: 'Premium_LRS'
- name: sqlConnectivityType
  value: 'Private'
- name: sqlAuthenticationLogin
  value: 'sqladmin'

steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.tfvars'

  inputs:
    rootDirectory: ./Student/Resources/terraform
    targetFiles: '**/*.tfvars'

- script: |
   terraform init \
       -backend-config="resource_group_name=$(tfstate_resource_group)" \
       -backend-config="storage_account_name=$(tfstate_storage_account)" \
       -backend-config="container_name=$(tfstate_container)" \
       -backend-config="key=$(tfstate_key)" \
       -backend-config="access_key=$(tfstate_access_key)"

  workingDirectory: ./Student/Resources/terraform
  displayName: 'Terraform init'


- script: |
   terraform apply -auto-approve \
       -var-file="terraform.tfvars"

  workingDirectory: ./Student/Resources/terraform
  displayName: 'Terraform apply'