queue:
  name: Hosted Ubuntu 1604


variables:
  tfstate_key: 'jimpaine.pre-ready-2019-H1.master.tfstate'
  resource_name: 'jp174'
  agent_count: '3'
  vm_size: 'Standard_B2ms'
  location: 'eastus'
  admin_user: 'demouser'
  k8s_version: '1.11.5'
  envPrefixName: 'jphack118'
  retentionPolicy: '90'
  sqlVmSize: 'Standard_DS3_v2'
  username: 'vmadmin'
  diskType: 'Premium_LRS'
  sqlConnectivityType: 'Private'
  sqlAuthenticationLogin: 'sqladmin'

steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.tfvars'

  inputs:
    rootDirectory: ./Student/Resources/terraform
    targetFiles: '**/*.tfvars'

- script: |
   ssh-keygen -t rsa -b 4096 -o -C "your_email@example.com" -f id_rsa

  workingDirectory: ./Student/Resources/terraform
  displayName: 'Generate SSH key'

- script: |
   terraform init \
       -backend-config="resource_group_name=$(tfstate_resource_group)" \
       -backend-config="storage_account_name=$(tfstate_storage_account)" \
       -backend-config="container_name=$(tfstate_container)" \
       -backend-config="key=$(tfstate_key)" \
       -backend-config="access_key=$(tfstate_access_key)"

  workingDirectory: ./Student/Resources/terraform
  displayName: 'Terraform init'


- script: |
   terraform apply -auto-approve \
       -var-file="terraform.tfvars"

  workingDirectory: ./Student/Resources/terraform
  displayName: 'Terraform apply'